# $Id$

test_init() {
    [ -z "$FDM" ] && exit 1

    TEST=${0%%.sh}

    rm -f $TEST.in $TEST.out $TEST.conf $TEST.data

    trap "rm -f $TEST.in $TEST.out $TEST.conf $TEST.data; exit 1" 2 3
}

test_in()
{
    cat >$TEST.in
}

test_out()
{
    cat >$TEST.out
}

test_run() {
    (
	echo "account \"test\" stdin"
	cat
	echo "match all action write \"$TEST.data\""
    ) >$TEST.conf
    chmod 600 $TEST.conf

    FLAGS=-q
    if [ "$DEBUG" != "" ]; then
	FLAGS=-vvv
    fi
    cat $TEST.in|$FDM $FLAGS -f $TEST.conf f || exit 1

    diff -u $TEST.out $TEST.data
    RESULT=$?
    if [ $RESULT -eq 0 ]; then
	echo "$0: PASSED"
    else
	echo "$0: FAILED"
    fi

    rm -f $TEST.in $TEST.out $TEST.conf $TEST.data

    exit $RESULT
}
